version: '3'

services:
  admin:
    #image: proiectidp_admin#
    build: ./admin
    volumes:
      - ./admin:/usr/src/app
    ports:
      - 5002:80
    expose:
      - 5002

  server:
    #image: proiectidp_server
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - db
    expose:
      - 5001

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  website:
    #image: proiectidp_website
    build: ./website
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - server


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "0"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

volumes:
    my-datavolume: {}
    grafana_data: {}

